--------------------------------------------------------------------------------
-- File: {{ app_name }}_custom_inst_shim.vhd
-- Generated: {{ timestamp }}
-- Generator: tools/generate_custom_inst_v2.py
-- Template Version: 2.0 (BasicAppDataTypes)
--
-- ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
-- This file is automatically generated from {{ yaml_file }}.
-- To modify, update the YAML file and regenerate.
--
-- Description:
--   Register mapping shim for {{ app_name }} with BasicAppDataTypes.
--   Maps raw Control Registers (CR6-CR15) to typed application signals
--   using automatic register packing from BADRegisterMapper.
--
-- Platform: {{ platform_name }}
-- Clock Frequency: {{ platform_clock_mhz }} MHz
--
-- Register Mapping ({{ mapping_strategy }} strategy):
{% for mapping in register_mappings %}
--   CR{{ mapping.register_index }}: {% for field in mapping.fields %}{{ field.name }} [{{ field.bits }}]{% if not loop.last %} | {% endif %}{% endfor %}
{% endfor %}
--   Total: {{ total_registers }} registers, {{ total_bits_used }}/{{ total_bits_available }} bits ({{ efficiency_percent }}% efficiency)
--
-- Architecture:
--   Layer 1: MCC_TOP_custom_inst_loader.vhd (static, shared)
--   Layer 2: {{ app_name }}_custom_inst_shim.vhd (THIS FILE - generated)
--   Layer 3: {{ app_name }}_custom_inst_main.vhd (application logic)
--
-- References:
--   - {{ yaml_file }}
--   - docs/BasicAppDataTypes/
--------------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

library WORK;
use WORK.custom_inst_common_pkg.all;
use WORK.basic_app_types_pkg.all;
{% if has_voltage_types %}use WORK.basic_app_voltage_pkg.all;
{% endif %}{% if has_time_types %}use WORK.basic_app_time_pkg.all;
{% endif %}
entity {{ app_name }}_custom_inst_shim is
    generic (
        CLK_FREQ_HZ : integer := {{ platform_clock_hz }}  -- {{ platform_name }} clock frequency
    );
    port (
        ------------------------------------------------------------------------
        -- Clock and Reset
        ------------------------------------------------------------------------
        Clk         : in  std_logic;
        Reset       : in  std_logic;  -- Active-high reset

        ------------------------------------------------------------------------
        -- VOLO Control Signals (from MCC_TOP_custom_inst_loader)
        ------------------------------------------------------------------------
        volo_ready  : in  std_logic;  -- CR0[31] - Set by loader
        user_enable : in  std_logic;  -- CR0[30] - User control
        clk_enable  : in  std_logic;  -- CR0[29] - Clock gating
        loader_done : in  std_logic;  -- BRAM loader FSM done signal

        ------------------------------------------------------------------------
        -- Handshaking Protocol
        ------------------------------------------------------------------------
        ready_for_updates : in  std_logic;  -- From main application

        ------------------------------------------------------------------------
        -- Application Registers (from MCC_TOP_custom_inst_loader)
        -- Control Registers CR6-CR15
        ------------------------------------------------------------------------
{% for cr_num in cr_numbers_used %}
        app_reg_{{ cr_num }} : in  std_logic_vector(31 downto 0){% if not loop.last %};{% endif %}
{% endfor %}
    );
end entity {{ app_name }}_custom_inst_shim;

architecture rtl of {{ app_name }}_custom_inst_shim is

    ----------------------------------------------------------------------------
    -- Typed Signal Declarations (BasicAppDataTypes)
    ----------------------------------------------------------------------------
{% for signal in signals %}
    signal {{ signal.name }} : {{ signal.vhdl_type }};  -- {{ signal.description }}
{% endfor %}

    ----------------------------------------------------------------------------
    -- Global Enable Signal
    ----------------------------------------------------------------------------
    signal global_enable : std_logic;

begin

    ----------------------------------------------------------------------------
    -- Global Enable Computation
    ----------------------------------------------------------------------------
    global_enable <= combine_volo_ready(volo_ready, user_enable, clk_enable, loader_done);

    ----------------------------------------------------------------------------
    -- Atomic Register Update Process
    --
    -- Extracts typed values from packed registers on rising_edge when
    -- ready_for_updates='1'. Type conversions use frozen VHDL packages.
    ----------------------------------------------------------------------------
    REGISTER_UPDATE_PROC: process(Clk)
    begin
        if rising_edge(Clk) then
            if Reset = '1' then
                -- Load default values from YAML specification
{% for signal in signals %}
    {% if signal.is_boolean %}
                {{ signal.name }} <= {% if signal.default_value %}'1'{% else %}'0'{% endif %};  -- {{ signal.description }}
    {% else %}
                {{ signal.name }} <= to_{{ signal.vhdl_base_type }}({{ signal.default_value }}, {{ signal.bit_width }});  -- {{ signal.description }}
    {% endif %}
{% endfor %}
            elsif ready_for_updates = '1' then
                -- Atomic update: Extract all typed values from packed registers
{% for signal in signals %}
    {% if signal.is_boolean %}
                {{ signal.name }} <= app_reg_{{ signal.cr_number }}({{ signal.bit_position }});  -- {{ signal.description }}
    {% elif signal.is_voltage %}
                {{ signal.name }} <= {{ signal.conversion_function }}_from_raw(app_reg_{{ signal.cr_number }}({{ signal.bit_range }}));  -- {{ signal.description }}
    {% elif signal.is_time %}
                {{ signal.name }} <= unsigned(app_reg_{{ signal.cr_number }}({{ signal.bit_range }}));  -- {{ signal.description }} (raw time value)
    {% else %}
                {{ signal.name }} <= {{ signal.vhdl_base_type }}(app_reg_{{ signal.cr_number }}({{ signal.bit_range }}));  -- {{ signal.description }}
    {% endif %}
{% endfor %}
            end if;
        end if;
    end process REGISTER_UPDATE_PROC;

    ----------------------------------------------------------------------------
    -- Main Application Instantiation
    ----------------------------------------------------------------------------
    MAIN_INST: entity WORK.{{ app_name }}_custom_inst_main
        generic map (
            CLK_FREQ_HZ => CLK_FREQ_HZ
        )
        port map (
            Clk                => Clk,
            Reset              => Reset,
            global_enable      => global_enable,
            ready_for_updates  => open,  -- Driven by main, connected here

            -- Application signals (typed)
{% for signal in signals %}
            {{ signal.name }}{% if signal.direction == 'output' %}_out{% endif %} => {{ signal.name }}{% if not loop.last %},{% endif %}
{% endfor %}
        );

end architecture rtl;
